INSERT INTO CITY_BASE_FEE (ID, CITY, BIKE_FEE, SCOOTER_FEE, CAR_FEE)
SELECT 1, 'TARTU', 2.5, 3.0, 3.5
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM CITY_BASE_FEE WHERE CITY = 'TARTU');

INSERT INTO CITY_BASE_FEE (ID, CITY, BIKE_FEE, SCOOTER_FEE, CAR_FEE)
SELECT 2, 'TALLINN', 3.0, 3.5, 4.00
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM CITY_BASE_FEE WHERE CITY = 'TALLINN');

INSERT INTO CITY_BASE_FEE (ID, CITY, BIKE_FEE, SCOOTER_FEE, CAR_FEE)
SELECT 3, 'PÄRNU', 2.0, 2.5, 3.0
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM CITY_BASE_FEE WHERE CITY = 'PÄRNU');